baseURL = 'https://traildeimaghe.it'
languageCode = 'it-IT'
theme = 'graysx'
title = 'Trail Dei Maghe'
contentDir = 'content'

## Site Settings
[params]
description = "Siete pronti per un'avventura indimenticabile immersi nella magia delle Dolomiti? Trail dei Maghe vi aspetta a Lorenzago di Cadore (BL) per una gara tra paesaggi incantevoli."
tags = ["dolomiti", "competizione", "gara", "corsa", "montagne", "cadore", "trail running"]
logo = "/assets/img/logo.png"
favicon = "/assets/favicon.png"
socialimage = "/assets/img/logo-black.png"

# Info
address = "Lorenzago di Cadore, Belluno - Dolomiti"
date = "16 Giugno 2024"
phone = "+39 331 939 7508"

# Socials
instagram = "https://www.instagram.com/traildeimaghe"

## Menu Items
[menu]
  [[menu.main]]
  name = "Storie e Leggende"
  URL = "/storie-e-leggende"
  weight = 1

  [[menu.main]]
  name = "Chi Siamo"
  URL = "/chi-siamo"
  weight = 2

  [[menu.main]]
  name = "ISCRIVITI"
  URL = "https://keepsporting.com/cr/65eab4721e801f41bd4b63c7/trail-dei-maghe?fbclid=IwAR28ydQrzrLJ8ypw33x8bd3JaLR8cWdzaXSZWsKX884PxYg-haIQak0TRYU"
  weight = 3