baseURL = 'http://example.org/'
languageCode = 'it-IT'
theme = 'graysx'
title = 'Trail Dei Maghe'

## Site Settings
[params]
logo = "assets/img/logo.png"
favicon = "assets/favicon.png"

# Info
address = "Lorenzago di Cadore, Belluno - Dolomiti"
date = "16 Giugno 2024"
phone = "+39 331 939 7508"

# Socials

twitter = "#"
facebook = "#"
instagram = "https://www.instagram.com/traildeimaghe"
github = "https://github.com/akatiggerx04/graysx-hugo"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "Storie e Leggende"
  URL = "/storie-e-leggende"
  weight = 1

  [[menu.main]]
  name = "Chi Siamo"
  URL = "/chi-siamo"
  weight = 2

  [[menu.main]]
  name = "ISCRIVITI"
  URL = "https://keepsporting.com/cr/65eab4721e801f41bd4b63c7/trail-dei-maghe?fbclid=IwAR28ydQrzrLJ8ypw33x8bd3JaLR8cWdzaXSZWsKX884PxYg-haIQak0TRYU"
  weight = 3


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04